#                            -*- mode: org; -*-
#
#+TITLE:                Pipe module for Youtoo 0.93
#+AUTHOR:               Rob Simmons and Andreas Kind
#+DATE:               July 1997; Updated February 2010
#+LINK:           http://www.cs.bath.ac.uk/~jap/ak1/youtoo
#+EMAIL: no-reply
#+OPTIONS: ^:{} email:nil

* [[file:COPYING][Copyright]]
    Youtoo is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Youtoo is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along with
    Youtoo in the file [[file:../../COPYING][COPYING]].  If not, see <http://www.gnu.org/licenses/>.

* [[file:../../index.org][EuLisp index]]

* General Description
  Library for pipes, forked child processes and control i/o with a stream
  object.

* Installation
  + Run 'make' in directory /Modules/Pipe/.
  + Run 'make test' in directory /Modules/Pipe/.
  + Add -lpipe to CLIBS in /youtoo/\.eulrc.${ARCH}/.

* Files
  The pipe library consists of single EuLisp module:
  - /pipe.em/ -- root module

  And a foreign-function interface file:
  - /eul-pipe.c/ -- C interface for pipe functions
