/** ----------------------------------------------------------------------- **
 **                 Generated by EuLisp System 'youtoo'
 ** ----------------------------------------------------------------------- **
 **  Description: C include file of EuLisp module i-args
 **  Copyright: See file i-args.em
 ** ----------------------------------------------------------------------- **/

extern LispRef i_args_bindings[];

/* Module binding indices */
#define print_help_fn_index 2 
#define parse_args_fn_index 4 
#define print_version_fn_index 5 
#define print_params_fn_index 3 



/* eof */
