#                            -*- mode: org; -*-
#
#+TITLE:               Match module for Youtoo 0.93
#+AUTHOR:
#+DATE:                        February 2010
#+LINK:           http://www.cs.bath.ac.uk/~jap/ak1/youtoo
#+EMAIL: no-reply
#+OPTIONS: ^:{} email:nil

* [[file:COPYING][Copyright]]
    Youtoo is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Youtoo is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along with
    Youtoo in the file [[file:../../COPYING][COPYING]].  If not, see <http://www.gnu.org/licenses/>.

* [[file:../../index.org][EuLisp index]]

* General Description
  Modulized version of match-slib.scm badly hacked for eulisp.

* Notes:
  + Vectors probably don't work right.
  + Why doesn't #(a b c ...) match what PLT Scheme gives for the same thing?
  + Structures certainly don't.
  + Use of modified vector-ref -- should original be changed?

* Installation
  + Run 'make' in directory /Extras/Match/.
  + Run 'make test' in directory /Extras/Match/.
