#                            -*- mode: org; -*-
#
#+TITLE:                Vmeta module for Youtoo 0.93
#+AUTHOR:                      T. Kurt Bond
#+DATE:                    Updated February 2010
#+LINK:           http://unwind-protect.org/~tkb/software.html
#+EMAIL: no-reply
#+OPTIONS: ^:{} email:nil

* [[file:COPYING][Copyright]]
    Youtoo is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    Youtoo is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along with
    Youtoo in the file [[file:../../COPYING][COPYING]].  If not, see <http://www.gnu.org/licenses/>.

* [[file:../../index.org][EuLisp index]]

* General Description
  This code was inspired by Henry G. Baker's article:
       "Pragmatic Parsing in Common Lisp",
       ACM LISP Pointers IV,2
       (April-June 1991), 3-15.

  However, any errors are mine; inefficencies too.  There have been some minor
  changes and additions from the code in that article.

  [[http://home.pipeline.com/~hbaker1][Original paper]]

* Installation
  + Run 'make' in directory /Extras/Vmeta/.
  + Run 'make test' in directory /Extras/Vmeta/.

* Files
  The pipe library consists of single EuLisp module:
  - /vmeta.em/ -- root module

  which uses the syntax operators in /vmeta-aux.em/
