#                            -*- mode: org; -*-
#
#+TITLE:              MPI Interface for Youtoo 0.93
#+AUTHOR:                     Andreas Kind
#+DATE:               July 1997; Updated February 2010
#+LINK:           http://www.cs.bath.ac.uk/~jap/ak1/youtoo
#+EMAIL: no-reply
#+OPTIONS: ^:{} email:nil

* [[file:COPYING][Copyright]]
    Youtoo is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Youtoo is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along with
    Youtoo in the file [[file:../../COPYING][COPYING]].  If not, see <http://www.gnu.org/licenses/>.

* [[file:../../index.org][EuLisp index]]

* General Description
  This directory contains the MPI connection for youtoo. Do the following to
  install it:

* Installation
  + Edit Makefile
  + Add the mpi library load path,
    e.g. -L/net/dominica/denton_export/MPI/mpich/lib/IRIX/ch_p4 to CFLAGS in
    your /~/\.eulrc.${ARCH}/
  + Bin.${ARCH}/youtoo -ar mpis -l level1
  + make
  + The headers in the examples will give you enough information how to compile
    them.
